-- Phase 1 of the compact editor-storage migration. Public lane IDs and all
-- legacy constraints remain in place throughout the dual-read/write rollout.
ALTER TABLE "canvas_lanes"
ADD COLUMN IF NOT EXISTS "lane_key" BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_canvas_lanes_lane_key"
ON "canvas_lanes" ("lane_key");

-- lane_note_effects was historically created by the editor API rather than a
-- Prisma migration. Creating it conditionally keeps a clean/staging database
-- safe while remaining a no-op for existing production databases.
CREATE TABLE IF NOT EXISTS "lane_note_effects" (
    "user_id" TEXT NOT NULL,
    "canvas_id" TEXT NOT NULL,
    "lane_id" TEXT NOT NULL,
    "effect_id" INTEGER NOT NULL,
    "effect_type" INTEGER NOT NULL,
    "start_note_id" INTEGER NOT NULL,
    "end_note_id" INTEGER NOT NULL,
    "effect_label" TEXT NOT NULL DEFAULT '',
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "lane_note_effects_pkey" PRIMARY KEY ("user_id", "canvas_id", "lane_id", "effect_id"),
    CONSTRAINT "lane_note_effects_canvas_lanes_fkey"
        FOREIGN KEY ("user_id", "canvas_id", "lane_id")
        REFERENCES "canvas_lanes" ("user_id", "canvas_id", "lane_id")
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_lane_note_effects_lookup"
ON "lane_note_effects" ("user_id", "canvas_id", "lane_id", "effect_id");

ALTER TABLE "lane_notes" ADD COLUMN IF NOT EXISTS "lane_key" BIGINT;
ALTER TABLE "lane_chords" ADD COLUMN IF NOT EXISTS "lane_key" BIGINT;
ALTER TABLE "lane_cuts" ADD COLUMN IF NOT EXISTS "lane_key" BIGINT;
ALTER TABLE "lane_note_effects" ADD COLUMN IF NOT EXISTS "lane_key" BIGINT;

-- Partial indexes do not index legacy NULL rows while the batched backfill is
-- running. The migration script validates every row before any old index can
-- be removed.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_lane_notes_compact_identity"
ON "lane_notes" ("lane_key", "note_id") WHERE "lane_key" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_lane_notes_compact_lookup"
ON "lane_notes" ("lane_key", "start_time", "note_id") WHERE "lane_key" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_lane_chords_compact_identity"
ON "lane_chords" ("lane_key", "chord_id") WHERE "lane_key" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_lane_chords_compact_lookup"
ON "lane_chords" ("lane_key", "start_time", "chord_id") WHERE "lane_key" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_lane_cuts_compact_identity"
ON "lane_cuts" ("lane_key", "region_index") WHERE "lane_key" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_lane_note_effects_compact_identity"
ON "lane_note_effects" ("lane_key", "effect_id") WHERE "lane_key" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "canvas_drafts" (
    "user_id" TEXT NOT NULL,
    "canvas_id" TEXT NOT NULL,
    "revision" BIGINT NOT NULL DEFAULT 1,
    "base_version" INTEGER NOT NULL DEFAULT 1,
    "snapshot" JSONB NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "canvas_drafts_pkey" PRIMARY KEY ("user_id", "canvas_id")
);

CREATE INDEX IF NOT EXISTS "idx_canvas_drafts_updated"
ON "canvas_drafts" ("updated_at");
